# Generated by Django 4.2.3 on 2023-09-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='mobile_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='voice_recording',
            field=models.FileField(default='', upload_to='voice/'),
        ),
    ]
